//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""b0d4caa8-5f04-45ae-bf35-a210444bda94"",
            ""actions"": [
                {
                    ""name"": ""Tree1"",
                    ""type"": ""Button"",
                    ""id"": ""3b3f9658-8327-430a-ae9e-074b3b609b59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree2"",
                    ""type"": ""Button"",
                    ""id"": ""cc5eb4b4-4de3-4c19-9cdc-a6e95efe4417"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree3"",
                    ""type"": ""Button"",
                    ""id"": ""edd1d96e-6b50-431d-ad80-2a002051a0a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree4"",
                    ""type"": ""Button"",
                    ""id"": ""baaff714-3e3d-4057-86f4-66543603b31e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree5"",
                    ""type"": ""Button"",
                    ""id"": ""a2eee900-6c13-40f0-a808-a0666f6efcb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree6"",
                    ""type"": ""Button"",
                    ""id"": ""d985402b-1744-4b2d-97b9-fb3ddbe7db93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree7"",
                    ""type"": ""Button"",
                    ""id"": ""a94dca10-9176-4a7f-9365-53eebd7220e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree8"",
                    ""type"": ""Button"",
                    ""id"": ""91e3f238-74ca-4197-a26b-d384f1db5b0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tree9"",
                    ""type"": ""Button"",
                    ""id"": ""3426072d-22ea-48ac-b334-58d69a288990"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HomeTree"",
                    ""type"": ""Button"",
                    ""id"": ""adaa914c-5d2e-4407-8a65-c307375edec5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c1f2b33-1808-41c4-9400-e33f0b154463"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6975c876-c80e-4d91-9287-b0fd79dd19d1"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9ec487d-bd6a-48fd-94e4-6c72be5df007"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cd3fd8f-665d-4ef3-b216-7fb4afee26df"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a45811ae-e5d8-480f-aa38-ab9b1c7a0338"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""268897a2-b49f-4782-960b-9287c7b99412"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41d69cd6-f209-4fdb-bf13-f276fc40ea20"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a802dbf-34a0-426c-ac69-9a60fd13ea62"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5393c7c6-890d-4670-961e-bd5644aa8ad0"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe9632ea-f108-49de-8bdc-6f6bdcd852b1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7457ea75-f1ee-4ec4-8f16-11f657010b86"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afe90497-338e-4af0-83f5-0e08d1e479b1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f469620e-e4ce-4da9-8620-73a628dd2561"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8c3b982-e2a7-432a-af1d-f0ae26b6c1b7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e6cb81d-4c53-4588-8702-329a0cde7b26"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c20f7e9b-cb3c-4a2e-b67c-9d1da17786c1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""948e214f-0a88-46f5-bf39-45dad744a0bc"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""177e4ed2-a573-4154-8940-aeee23984dad"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tree9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7dee312-d107-4096-bb96-e861f0cf7322"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HomeTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1c7c901-d67b-442a-b44d-811963f811d7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HomeTree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Tree1 = m_Player.FindAction("Tree1", throwIfNotFound: true);
        m_Player_Tree2 = m_Player.FindAction("Tree2", throwIfNotFound: true);
        m_Player_Tree3 = m_Player.FindAction("Tree3", throwIfNotFound: true);
        m_Player_Tree4 = m_Player.FindAction("Tree4", throwIfNotFound: true);
        m_Player_Tree5 = m_Player.FindAction("Tree5", throwIfNotFound: true);
        m_Player_Tree6 = m_Player.FindAction("Tree6", throwIfNotFound: true);
        m_Player_Tree7 = m_Player.FindAction("Tree7", throwIfNotFound: true);
        m_Player_Tree8 = m_Player.FindAction("Tree8", throwIfNotFound: true);
        m_Player_Tree9 = m_Player.FindAction("Tree9", throwIfNotFound: true);
        m_Player_HomeTree = m_Player.FindAction("HomeTree", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Tree1;
    private readonly InputAction m_Player_Tree2;
    private readonly InputAction m_Player_Tree3;
    private readonly InputAction m_Player_Tree4;
    private readonly InputAction m_Player_Tree5;
    private readonly InputAction m_Player_Tree6;
    private readonly InputAction m_Player_Tree7;
    private readonly InputAction m_Player_Tree8;
    private readonly InputAction m_Player_Tree9;
    private readonly InputAction m_Player_HomeTree;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tree1 => m_Wrapper.m_Player_Tree1;
        public InputAction @Tree2 => m_Wrapper.m_Player_Tree2;
        public InputAction @Tree3 => m_Wrapper.m_Player_Tree3;
        public InputAction @Tree4 => m_Wrapper.m_Player_Tree4;
        public InputAction @Tree5 => m_Wrapper.m_Player_Tree5;
        public InputAction @Tree6 => m_Wrapper.m_Player_Tree6;
        public InputAction @Tree7 => m_Wrapper.m_Player_Tree7;
        public InputAction @Tree8 => m_Wrapper.m_Player_Tree8;
        public InputAction @Tree9 => m_Wrapper.m_Player_Tree9;
        public InputAction @HomeTree => m_Wrapper.m_Player_HomeTree;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Tree1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree1;
                @Tree1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree1;
                @Tree1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree1;
                @Tree2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree2;
                @Tree2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree2;
                @Tree2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree2;
                @Tree3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree3;
                @Tree3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree3;
                @Tree3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree3;
                @Tree4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree4;
                @Tree4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree4;
                @Tree4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree4;
                @Tree5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree5;
                @Tree5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree5;
                @Tree5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree5;
                @Tree6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree6;
                @Tree6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree6;
                @Tree6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree6;
                @Tree7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree7;
                @Tree7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree7;
                @Tree7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree7;
                @Tree8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree8;
                @Tree8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree8;
                @Tree8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree8;
                @Tree9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree9;
                @Tree9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree9;
                @Tree9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTree9;
                @HomeTree.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTree;
                @HomeTree.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTree;
                @HomeTree.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHomeTree;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Tree1.started += instance.OnTree1;
                @Tree1.performed += instance.OnTree1;
                @Tree1.canceled += instance.OnTree1;
                @Tree2.started += instance.OnTree2;
                @Tree2.performed += instance.OnTree2;
                @Tree2.canceled += instance.OnTree2;
                @Tree3.started += instance.OnTree3;
                @Tree3.performed += instance.OnTree3;
                @Tree3.canceled += instance.OnTree3;
                @Tree4.started += instance.OnTree4;
                @Tree4.performed += instance.OnTree4;
                @Tree4.canceled += instance.OnTree4;
                @Tree5.started += instance.OnTree5;
                @Tree5.performed += instance.OnTree5;
                @Tree5.canceled += instance.OnTree5;
                @Tree6.started += instance.OnTree6;
                @Tree6.performed += instance.OnTree6;
                @Tree6.canceled += instance.OnTree6;
                @Tree7.started += instance.OnTree7;
                @Tree7.performed += instance.OnTree7;
                @Tree7.canceled += instance.OnTree7;
                @Tree8.started += instance.OnTree8;
                @Tree8.performed += instance.OnTree8;
                @Tree8.canceled += instance.OnTree8;
                @Tree9.started += instance.OnTree9;
                @Tree9.performed += instance.OnTree9;
                @Tree9.canceled += instance.OnTree9;
                @HomeTree.started += instance.OnHomeTree;
                @HomeTree.performed += instance.OnHomeTree;
                @HomeTree.canceled += instance.OnHomeTree;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnTree1(InputAction.CallbackContext context);
        void OnTree2(InputAction.CallbackContext context);
        void OnTree3(InputAction.CallbackContext context);
        void OnTree4(InputAction.CallbackContext context);
        void OnTree5(InputAction.CallbackContext context);
        void OnTree6(InputAction.CallbackContext context);
        void OnTree7(InputAction.CallbackContext context);
        void OnTree8(InputAction.CallbackContext context);
        void OnTree9(InputAction.CallbackContext context);
        void OnHomeTree(InputAction.CallbackContext context);
    }
}
